name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - feature/hf-space
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub[cli]==0.26.2

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          if [ -z "$HF_TOKEN" ] || [ -z "$SPACE_ID" ]; then
            echo "HF_TOKEN and HF_SPACE_ID secrets are required" && exit 1
          fi
          python - << 'PY'
from huggingface_hub import HfApi
import os
repo_id = os.environ['SPACE_ID']
api = HfApi(token=os.environ['HF_TOKEN'])
# Upload key project files
paths = [
  'app.py','requirements.txt','Procfile','README.md',
  'templates/dashboard.html','templates/index.html'
]
for p in paths:
  if os.path.exists(p):
    api.upload_file(path_or_fileobj=p, path_in_repo=p, repo_id=repo_id, repo_type='space')
# Upload src directory recursively
if os.path.isdir('src'):
  api.upload_folder(folder_path='src', repo_id=repo_id, repo_type='space', path_in_repo='src')
PY 